name: build_wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]
    env:
      # Skip building on Python 2.7 on all platforms:
      CIBW_SKIP: cp27-*
      # Need an up-to-date pip:
      update_pip: "python -m pip install --upgrade pip"
      # Need to install p2p depedencies:
      p2p_deps: "python -m pip install -r requirements.txt"
      CIBW_BEFORE_BUILD: "$(update_pip) && $(p2p_deps)"
      # On Linux, need to install Matplotlib depedencies in Docker container:
      mpl_deps: "yum -y install freetype-devel pkg-config libpng-devel"
      CIBW_BEFORE_BUILD_LINUX: "$(mpl_deps) && $(update_pip) && $(p2p_deps)"

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v1
      name: Install Python
      with:
        python-version: '3.7'

    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==1.4.1
    - name: Build wheel
      run: |
        python -m cibuildwheel --output-dir wheelhouse
    - uses: actions/upload-artifact@v1
      with:
        name: wheels
        path: ./wheelhouse